### ISSUE TITLE
depth processing seems not to work

### ISSUE THREAD

**Issue by stevo01** [OpenSeaMap/depth_webfrontend#238]
I checked the database and saw many tracks uploaded from 2023 to 2024. They all show a status of "1" since January 8, 2023. It seems like the track upload is fine, but there might be a problem with the depth processing part.

**Comment by stevo01** [comment]
logfile shows following entry:
```
!SESSION 2023-08-11 10:13:49.805 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_252
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -console

!ENTRY net.sf.seesea.data.io.postgis 4 0 2023-08-11 10:13:50.494
!MESSAGE [net.sf.seesea.data.io.postgis.PostInsertGISWriter(4)] The activate method has thrown an exception
!STACK 0
org.postgresql.util.PSQLException: Connection to localhost:5435 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:215)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
```

note:
I checked all config files and can confirm that "localhost" is not used, All config files include following entries for hostname and port:
```
server=postgis
port=5435
```

**Comment by stevo01** [comment]
I made a new build of the software this week and deployed it to server. I found following error in the logfile:

```
org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "172.18.0.2", user "osm", database "depth", SSL off
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:443)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:217)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:215)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
	at org.postgresql.Driver.connect(Driver.java:272)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:86)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:71)
	at net.sf.seesea.data.io.postgis.PostInsertGISWriter.activate(PostInsertGISWriter.java:94)
```

After I changed the password in the following logfiles, the error is gone.
```
./config/net.sf.seesea.data.io.postgis.PostgresDatasourceConfiguration-depth.cfg.
./config/net.sf.seesea.data.io.postgis.PostgresDatasourceConfiguration-userdata.cfg

```
